stages:
  - test
  - build

test-node-8:
  stage: test
  image: node:8
  script:
    - npm install
    - NODE_ENV=test npm test

test-node-9:
  stage: test
  image: node:9
  script:
    - npm install
    - NODE_ENV=test npm test

test-node-10:
  stage: test
  image: node:9
  script:
    - npm install
    - NODE_ENV=test npm test

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
