cache:
  directories:
    - node_modules

language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"

env: 
  - NODE_ENV=test

before_script:
  - npm run watch &
  - sleep 2s

script: npm run spec
